# Power Method

#### By: Dr H.Haghbin

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[1,2],
             [-1,2],
             [1,-2],
             [-1,-2]])
x0 = np.array([1,1])

In [3]:
n, d = A.shape
delta = 0.01

In [23]:
Ax = np.matmul(A,x0)
Bx = np.matmul(A.transpose(),Ax)
x1 = Bx / LA.norm(Bx)
delta = LA.norm(x1 - x0)
x0 = x1

In [24]:
x1

array([9.76562034e-04, 9.99999523e-01])

In [25]:
delta

0.002929666894690846

In [26]:
def power_iteration(A):
    n, d = A.shape
    x = np.ones(d) / np.sqrt(d)
    delta = 0.01
    while True:
        Ax = np.matmul(A,x)
        Bx = np.matmul(A.transpose(),Ax)
        x_new = Bx / LA.norm(Bx)
        delta = LA.norm(x_new - x)
        if delta < 0.001:
            break
        x = x_new
    return x

In [27]:
power_iteration(A)

array([9.76562034e-04, 9.99999523e-01])

In [28]:
v1 = power_iteration(A)
np.round(v1,4)

array([0.001, 1.   ])

In [29]:
s1= LA.norm(np.matmul(A,v1))
s1

3.999998569489634

In [30]:
u1 = np.matmul(A,v1)/s1
u1

array([ 0.50024408,  0.4997558 , -0.4997558 , -0.50024408])

In [31]:
A_new = A-s1*np.outer(u1,v1)

In [32]:
A_new

array([[ 9.98045923e-01, -9.74654222e-04],
       [-1.00195217e+00,  9.78468915e-04],
       [ 1.00195217e+00, -9.78468915e-04],
       [-9.98045923e-01,  9.74654222e-04]])

In [33]:
v2 = power_iteration(A_new)
np.round(v2,4)

array([ 1.   , -0.001])

In [34]:
s2= LA.norm(np.matmul(A,v2))
s2

2.0000028610181744

In [35]:
u2 = np.matmul(A,v2)/s2
u2

array([ 0.49902249, -0.50097561,  0.50097561, -0.49902249])

## Compare with SVD 

In [103]:
U,M,V = LA.svd(A, full_matrices=False)

In [104]:
U

array([[-0.5, -0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5,  0.5]])

In [105]:
M

array([4., 2.])

In [106]:
V

array([[-0., -1.],
       [-1., -0.]])